language: ruby
rvm:
- 2.4.2
services:
  - postgresql
addons:
  - postgresql: "9.6"
before_install:
  - gem install bundler -v 1.16.1
before_script:
  - psql -c 'create database travis_ci_db' -U postgres
notifications:
  email:
    on_success: always
    on_failure: always
